apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
        - name: go-hello
          image: himanshu162pnt723/go-hello:latest
          ports:
            - containerPort: 8080
