apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goapp
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts
      sourceRef:
        kind: GitRepository
        name: goapp
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: himanshu162pnt723/goapp
      tag: "20250908160902" # {"$imagepolicy": "flux-system:goapp"}
    service:
      type: NodePort
      port: 8080

