apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: goapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: goapp
  policy:
    alphabetical:
      order: desc  # or "desc" for newest
