apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: goapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: goapp
  filterTags:
    # Match only tags that are pure 14-digit numbers like 20250909122248
    pattern: '^(?P<ts>[0-9]{14})$'
    extract: '$ts'
  policy:
    numerical:
      order: asc   # pick the latest timestamp (biggest number)
