apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: goapp
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/cluster        # ← point to the folder with your HelmRelease
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
