name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: himanshu162pnt723/goapp

jobs:
  build:
    runs-on: ubuntu-latest

    # ✅ Skip job if commit author is fluxcdbot
    if: github.actor != 'fluxcdbot'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate short timestamp
        id: timestamp
        run: echo "SHORT_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.SHORT_TAG }}
