name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: himanshu162pnt723/goapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit Author
        id: commit
        run: |
          AUTHOR=$(git log -1 --pretty='%an')
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV
          echo "Commit Author: $AUTHOR"
          echo "GitHub Actor: $GITHUB_ACTOR"

      - name: Stop if commit author is fluxcdbot
        if: env.AUTHOR == 'fluxcdbot'
        run: |
          echo "Commit was made by fluxcdbot, skipping build & push."
          exit 0

      - name: Log in to DockerHub
        if: env.AUTHOR != 'fluxcdbot'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: env.AUTHOR != 'fluxcdbot'
        uses: docker/setup-buildx-action@v2

      - name: Generate short timestamp
        if: env.AUTHOR != 'fluxcdbot'
        id: timestamp
        run: echo "SHORT_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker image
        if: env.AUTHOR != 'fluxcdbot'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.SHORT_TAG }}
